on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node_version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: install libpng and ragel for MacOS
      if: matrix.os == 'macOS-latest'
      run: |
        brew update
        brew install libpng ragel
    - uses: Et7f3/esy-actions@v1.0.0
